// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTYXbMJXYyfOkmidfrSuPKBK_HCj-BgV8',
    appId: '1:499525695120:web:54163c0744009166600a15',
    messagingSenderId: '499525695120',
    projectId: 'chat-app-v-1-dfad2',
    authDomain: 'chat-app-v-1-dfad2.firebaseapp.com',
    storageBucket: 'chat-app-v-1-dfad2.firebasestorage.app',
    measurementId: 'G-R4PBHFY2HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx44CYjP8A2CASQovXL-OfDSGhZQcAL9I',
    appId: '1:499525695120:android:8402810f2f5460d1600a15',
    messagingSenderId: '499525695120',
    projectId: 'chat-app-v-1-dfad2',
    storageBucket: 'chat-app-v-1-dfad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa2KSfTduSrVcT1j6IWiWUWkR7NtgtbIA',
    appId: '1:499525695120:ios:fda7b7b702357de9600a15',
    messagingSenderId: '499525695120',
    projectId: 'chat-app-v-1-dfad2',
    storageBucket: 'chat-app-v-1-dfad2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
